export enum GeneratorName {
  appGroupingFolder = "appGroupingFolder",
  domainGroupingFolder = "domainGroupingFolder",
  moveGroupingFolder = "moveGroupingFolder",
  removeGroupingFolder = "removeGroupingFolder",
  ngApplicationLayer = "ngApplicationLayer",
  ngComponent = "ngComponent",
  ngComponentGlobalStyles = "ngComponentGlobalStyles",
  ngDataAccessLayer = "ngDataAccessLayer",
  ngDirective = "ngDirective",
  ngDomainLayer = "ngDomainLayer",
  ngUtilLayer = "ngUtilLayer",
  domainTest = "domainTest",
  ngRemoveLibrary = "ngRemoveLibrary",
  mockFile = "mockFile",
  lint = "lint",
  test = "test",
  ct = "ct",
  e2e = "e2e",
}
